---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  - name: mysqld-exporter
    port: 9104
    targetPort: 9104
    protocol: TCP
  selector:
    app: mysql
  #clusterIP: None
