apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: prometheus-config
  namespace: monitoring 
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 1m
    #alerting:
    #  alertmanagers:
    #  - static_configs:
    #    - targets:
    #      - alertmanager.monitoring.svc.cluster.local:9093
    #rule_files:
    #- "/etc/prometheus/rules/rule1.yaml"
    scrape_configs:
    - job_name: 'hw_prometheus'
      static_configs:
      - targets: ['localhost:9090']
      metrics_path: '/hw_prometheus/metrics'

    # Scape config for prometheus node exporters.
    #
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__
        action: replace
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
    #  static_configs:
    #  - targets: ['10.0.0.10:9100','10.0.0.11:9100']

    #- job_name: 'cadvisor'
    #  static_configs:
    #  - targets: ['10.0.0.10:8080','10.0.0.11:8080']
    #- job_name: 'kube-state-metrics'
    #  static_configs:
    #  - targets: ['kube-state-system.kube-system.svc.cluster.local:8080']
    #- job_name: 'mysqld-exporter'
    #  static_configs: 
    #  - targets: ['mysql.mysql.svc.cluster.local:9104']
    #- job_name: 'kube-dns'
    #  static_configs:
    #  - targets: ['kube-dns.kube-system.svc.cluster.local:9153']
    #- job_name: 'ingress-nginx-controller'
    #  static_configs:
    #  - targets: ['ingress-nginx-controller.ingress-nginx.svc.cluster.local:10254']
    #- job_name: 'etcd'
    #  scheme: https
    #  tls_config:
    #    ca_file: /etc/prometheus/tls/etcd/ca.pem
    #    cert_file: /etc/prometheus/tls/etcd/etcd.pem
    #    key_file: /etc/prometheus/tls/etcd/etcd-key.pem
    #    insecure_skip_verify: true
    #  static_configs:
    #  - targets: ['10.0.0.10:2379']
    #- job_name: 'calico-node'
    #  static_configs: 
    #  - targets: ['calico-node-metrics.kube-system.svc.cluster.local:9091']
    #- job_name: 'calico-kube-controllers'
    #  static_configs:
    #  - targets: ['calico-kube-controllers-metrics.kube-system.svc.cluster.local:9094']
    #- job_name: 'tomcat'
    #  static_configs:
    #  - targets: ['tomcat-jpress-svc.blogs.svc.cluster.local:8081']
    #- job_name: 'elasticsearch'
    #  static_configs:
    #  - targets: ['es-svc.elk.svc.cluster.local:9114']
