---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-nfs
  namespace: mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi-sc
