---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-jpress-svc
  namespace: blogs
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 8081
    targetPort: 8081
    protocol: TCP
  #clusterIP: None
  selector:
    app: tomcat
