---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tomcat-jpress-pvc-nfs
  namespace: blogs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi-sc
